server:
  port: 8861

eureka:
  client:
    service-url: #Eureka Server地址
      defaultZone: http://www.eureka-node2.com:8862/eureka/,http://www.eureka-node3.com:8863/eureka/
  instance:
    hostname: www.eureka-node1.com

spring:
  application:
    name: server-eureka